services:
  - type: web
    name: hostaway-assessment-api
    runtime: node
    plan: free
    buildCommand: pwd && ls -la && npm ci && npm run build && ls -la dist/
    startCommand: pwd && ls -la && node /opt/render/project/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENWEATHER_API_URL
        value: https://api.openweathermap.org
    healthCheckPath: /api/weather/health
