services:
  - type: web
    name: hostaway-assessment-api
    runtime: node
    plan: free
    buildCommand: npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENWEATHER_API_URL
        value: https://api.openweathermap.org
    healthCheckPath: /api/weather/health
