services:
  - type: web
    name: hostaway-assessment-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:debug
    envVars:
      - key: NODE_ENV
        value: production
      # Note: MONGODB_URI, MONGODB_DB_NAME, OPENWEATHER_API_KEY, and JWT_SECRET
      # must be set manually in Render dashboard as secret environment variables
      - key: PORT
        value: 4000
      - key: OPENWEATHER_API_URL
        value: https://api.openweathermap.org
    healthCheckPath: /api/weather/health
