services:
  - type: web
    name: hostaway-assessment-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: MONGODB_DB_NAME
        value: hostaway
      - key: PORT
        value: 4000
      - key: OPENWEATHER_API_KEY
        sync: false # Set this as a secret environment variable in Render dashboard
      - key: OPENWEATHER_API_URL
        value: https://api.openweathermap.org
      - key: JWT_SECRET
        sync: false # Set this as a secret environment variable in Render dashboard
    healthCheckPath: /api/weather/health
