services:
  - type: web
    name: hostaway-assessment-api
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: OPENWEATHER_API_URL
        value: https://api.openweathermap.org
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 60000
    healthCheckPath: /api/weather/health
